### ISSUE TITLE
Missing meta data

### ISSUE THREAD

**Issue by sarigs** [CheckPointSW/Scout#17]
Dear Developer, 

 For readability and Search Engine Optimization (SEO) it would be great if you could do the followings:
- [ ] Please provide more than 8 words in the "About" field
- [ ] Please provide relevant "Topics" 
>**Environment topic examples**:
>azure, aws, gcp
>**Functionality topic examples**:
>**build**, **deploy**, **staging**, **operate**, terraform, ansible, helm, android, cloudguardIaaS, management, gaia, threat-prevention, identity-awareness, smp, iot, cloudguard-connect, cloudguard-dome9, malware, evasion

**Comment by chkp-eyalit** [comment]
Sorry, I don't think that the automatic script that generated this issue is relevant whatsoever to this repository. This is a research tool, and most of the terminology that was used in the issue's description is totally irrelevant.
