### ISSUE TITLE
Fix a leftover port from python2

### ISSUE THREAD

**Issue by turtiustrek** [CheckPointSW/Scout#20]
in file,

```
--- context_creator.py   
+++context_creator.py 
+    got =b''
-    got = ''
+    got += b'\x00' * globals_size
-    got += '\x00' * globals_size
     # functions
     return got
 ```

**Comment by chkp-eyalit** [comment]
Hi, sorry about the late response, I missed the notification about this issue.
I tested it now in an end-to-end test on our internal CTF challenge, while only using python3, and it worked like a charm.

**Comment by chkp-eyalit** [comment]
You are right about the thumb support, checked it again now and the fix in on it's way. See issue #22

**Comment by turtiustrek** [comment]
Awesome! Thanks for that
